### ISSUE TITLE
Multiple Weapons?

### ISSUE THREAD

**Issue by Thundros** [karozaj/Stormwave#2] opened 2024-12-20 19:29 UTC
Hi there, @karozaj, @Dexter1245639, @Gamowy, @MarekGrys ! First off everyone, I must say **please** keep working on this! It is an **amazing** project with **much** potential! I absolutely **adore** this project !!! Next, I would like to ask if you could fix the multiple weapon bug and show me in exactly which script I should change what.

Here's a screenshot of what happened when I scrolled through the weapons too fast: 

![image](https://github.com/user-attachments/assets/6580cea2-62f1-4d83-bc82-cd68d15d9c15)

Yes, I edited the health a little bit and added some of my own script which has nothing to do with the problem at hand.

I thank you, look forward to seeing your reply and I hope you all have a very Merry Christmas!

P.S. What license are you currently using for all of this project including models, sounds, etc... ?

**Comment by Thundros** [comment] 2024-12-22 17:30
Hello?

**Comment by karozaj** [comment] 2024-12-22 22:16
Hi, thanks for letting us know about the issue! It will be fixed soon, it was caused by the animations being interrupted when switching weapons too quickly, resulting in the previous weapon not getting hidden. As for the license, we'll let you know soon, we're also using some third party assets alongside our original ones, so there will be a list detailing all that.
Merry Christmas!

**Comment by Thundros** [comment] 2024-12-23 15:15
@karozaj Thank you so much for this! This project means the world to me! Merry Christmas to you as well!

**Closed as completed** 2024-12-27 12:46 UTC

**Comment by Thundros** [comment] 2024-12-27 16:36
@karozaj thank you for fixing all of this! One more thing. What script do I need to change to fix the weapons bug? Also, can you add the copyrights? Much thanks / appreciation! <3
